# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identy_index', models.CharField(max_length=30)),
                ('left_top_pos', models.CharField(max_length=30)),
                ('remark_pos', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RPDVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=30)),
                ('quadraticTops', models.TextField(null=True)),
                ('conntype_hollow', models.BooleanField(default=False)),
                ('tongue_cover', models.BooleanField(default=False)),
                ('maxilla_cover', models.BooleanField(default=False)),
                ('innerPathList', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(null=True)),
                ('tooth_lost', models.IntegerField(null=True)),
                ('tooth_base', models.IntegerField(null=True)),
                ('tooth_clasp', models.IntegerField(null=True)),
                ('tooth_support', models.IntegerField(null=True)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpdesign.RPDVisit')),
            ],
        ),
        migrations.AddField(
            model_name='remark',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpdesign.RPDVisit'),
        ),
    ]
